version: 2.1

orbs:
  node: circleci/node@5.2

jobs:
  build-and-test:
    docker:
      - image: cimg/node:16.10

    steps:
      - checkout

      # Specify the directory where package.json is located
      # Change 'client_code' to 'server' if the package.json is in that directory
      - node/install-packages:
          pkg-manager: npm
          app-dir: client_code  # Change this to server if necessary

      - run:
          name: Run tests
          command: |
            cd client_code  # Change to server if necessary
            npm run dev

workflows:
  version: 2
  build:
    jobs:
      - build-and-test
